In [1]:
#Write a numpy program to create an element-wise comparison(greater,greater_equal,less,less_equal)of two given arrays.
import numpy as np
x=np.array([5,6])
y=np.array([7,8])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x,y))
print("Comparison - greater_equal")
print(np.greater_equal(x,y))
print("Comparison - less")
print(np.less(x,y))
print("Comparison - less_equal")
print(np.less_equal(x,y))

Original numbers:
[5 6]
[7 8]
Comparison - greater
[False False]
Comparison - greater_equal
[False False]
Comparison - less
[ True  True]
Comparison - less_equal
[ True  True]


In [4]:
#Write a numpy program to create an array of all the even integers from 30 to 70.
import numpy as np
array=np.arange(30,71,2)
print("Array of all even integers from 30 to 70")
print(array)

Array of all even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [5]:
#Write a NumPy program to create a 3*3 identity matrix.
import numpy as np
array_2D=np.identity(3)
print('3*3 matrix:')
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#write a numpy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15
import numpy as np
x=np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x>=9)&(x<=15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [9]:
#Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [17]:
#Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
import numpy as np
x = np.array([[5,8],[5,6]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[5 8]
 [5 6]]
Sum of all elements:
24
Sum of each column:
[10 14]
Sum of each row:
[13 11]


In [11]:
#Write a NumPy program to save a given array to a text file and load it.
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [16]:
#Write a NumPy program to check whether two arrays are equal (element wise) or not.
import numpy as np
nums1 = np.array([2,6,9])
nums2 = np.array([5,10,15])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)


Original arrays:
[2 6 9]
[ 5 10 15]

Test said two arrays are equal (element wise) or not:?
[False False False]


In [13]:
#Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.


import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
new_nums = nums[::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [18]:
#Write a NumPy program to multiply two given arrays of same size element-by-element.
import numpy as np 
nums1 = np.array([[4 ,5, 8],
              [4, 9, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[4 5 8]
 [4 9 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[20 15 32]
 [12 18 25]]
