In [1]:
#2.1
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Read elements from single line seperated by space: ")
    arr_1 = map(int, input().split())
    arr_1 = np.array(list(arr_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  Enter row size and column size: ")
    row,column = map(int, input().split())
    if(len(arr_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! try again")
        return create_matrix(mc)
    arr_1 = arr_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(arr_1)
    return arr_1


array_1 = create_matrix(1)
array_2 = create_matrix(2)

if(array_1.shape == array_2.shape):
    print("\nDot product is")
    print(np.dot(array_1,array_2))
else:
    print("\nUnmatching Dimensions!")


ARRAY 1 Read elements from single line seperated by space: 
2 4 6 8 1 3 5 9 8

ARRAY 1 ,  Enter row size and column size: 
3 3

ARRAY 1
[[2 4 6]
 [8 1 3]
 [5 9 8]]

ARRAY 2 Read elements from single line seperated by space: 
1 2 3 4 5 6 7 8 9

ARRAY 2 ,  Enter row size and column size: 
3 3

ARRAY 2
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dot product is
[[ 60  72  84]
 [ 33  45  57]
 [ 97 119 141]]


In [2]:
#2.2
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+"Read elements from single line seperated by space : ")
    arr_1 = map(int, input().split())
    arr_1 = np.array(list(arr_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" , Enter the row size and column size: ")
    row,column = map(int, input().split())
    if(len(arr_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    arr_1 = arr_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(arr_1)
    print("\nTranspose : ")
    return arr_1



print(create_matrix(1).transpose())



ARRAY 1Read elements from single line seperated by space : 
1 2 3 4 5 6 7 8 9

ARRAY 1 , Enter the row size and column size: 
3 3

ARRAY 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
#2.3
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Read elements from a single line seperated by space: ")
    arr_1 = map(int, input().split())
    arr_1 = np.array(list(arr_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" , Enter row size and column size : ")
    row,column = map(int, input().split())
    if(len(arr_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    arr_1 = arr_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(arr_1)
    print("\nTrase is: ")
    return arr_1



print(create_matrix(1).trace())


ARRAY 1 Read elements from a single line seperated by space: 
1 2 3 4 5 6 7 8 9

ARRAY 1 , Enter row size and column size : 
3 3

ARRAY 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trase is: 
15


In [6]:
#2.4
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Read elements from a single line seperated by space: ")
    arr_1 = map(int, input().split())
    arr_1 = np.array(list(arr_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  enter row size and column size : ")
    row,column = map(int, input().split())
    if(len(arr_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    arr_1 = arr_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(arr_1)
    print("\nRank : ")
    return arr_1



print(np.linalg.matrix_rank(create_matrix(1)))




ARRAY 1 Read elements from a single line seperated by space: 
1 2 3 4 5 6 7 8 9

ARRAY 1 ,  enter row size and column size : 
3 3

ARRAY 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank : 
2
