In [13]:
import numpy as np
x=np.array([1,5])
y=np.array([3,6])
print("Print original numbers :")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x,y))
print("Comparison - greater_equal")
print(np.greater_equal(x,y))
print("Comparison - equal")
print(np.less(x,y))
print("Comparison - less_equal")
print(np.less_equal(x,y))

Print original numbers :
[1 5]
[3 6]
Comparison - greater
[False False]
Comparison - greater_equal
[False False]
Comparison - equal
[ True  True]
Comparison - less_equal
[ True  True]


In [12]:
import numpy as np
array=np.arange(30,71,2)
print("Array of integers from 30 to 70 : ")
print(array)

Array of integers from 30 to 70 : 
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
